Updated 2018 guidelines
HackIllinois/Submissions-Guidelines pull request #4
Opened 2018-02-21 05:11 UTC by apache8080

2018-02-21 05:12 UTC, narendasan requested changes

2018-02-21 05:12 UTC, narendasan commented on README.md
> +* If you made an Open Source contribution click[here](https://github.com/HackIllinois/Submissions-Guidelines/tree/master/contribute)
space needed here

2018-02-21 05:12 UTC, narendasan commented on contribute/contribute.md
> +As an attendee who made open source contributions, your submission will consist of a [devpost](https://hackillinois-2017.devpost.com/) submission and a link to a GitHub gist.
Update the devpost link

2018-02-21 05:12 UTC, narendasan commented on create/create.md
> +As an attendee who developed a new project, your submission should consist of a [devpost](https://hackillinois-2017.devpost.com/) submission, public code repository, as well as (at least) three speci
update devpost link

2018-02-21 06:23 UTC, redsn0w422 commented
@apache8080 are we not renaming the folders? One way to get around this is to just put all the info in one file. The problem with having folders is that it has the issue of dividing the event.

2018-02-21 06:41 UTC, apache8080 commented
Just renamed them. I forgot about doing that on my previous commit.

2018-02-21 06:51 UTC, redsn0w422 requested changes
I think putting them all in one file is a good idea. Can you do that?

2018-02-22 07:30 UTC, aashishkapur commented
@apache8080 Devpost does not exist, @redsn0w422 will create soon, update the link once it's made

2018-02-22 20:49 UTC, apache8080 commented
So we can put it all in one file, but I don't know how to link to specific headings in markdown. Do you know how to do that?

2018-02-22 21:02 UTC, aashishkapur commented
@apache8080 https://gist.github.com/asabaylus/3071099

2018-02-23 02:40 UTC, apache8080 commented
One page now.

2018-02-23 03:35 UTC, redsn0w422 requested changes

2018-02-23 03:35 UTC, redsn0w422 commented on README.md
> +- Proper use of source control
Can we include examples of what good source control usage looks like?

2018-02-23 21:23 UTC, merged